
module.exports = [
    { en_name: 'guangdong', name: '广东',long_name:'广东省' },
    { en_name: 'beijing', name: '北京',long_name:'北京市' },
    { en_name: 'tianjin', name: '天津' ,long_name:'天津市'},
    { en_name: 'hebei', name: '河北',long_name:'河北省' },
    { en_name: 'liaoning', name: '辽宁',long_name:'辽宁省' },
    { en_name: 'jilin', name: '吉林',long_name:'吉林省' },
    { en_name: 'heilongjiang', name: '黑龙江',long_name:'黑龙江省' },
    { en_name: 'shandong', name: '山东',long_name:'山东省' },
    { en_name: 'jiangsu', name: '江苏' ,long_name:'江苏省'},
    { en_name: 'shanghai', name: '上海',long_name:'上海市' },
    { en_name: 'zhejiang', name: '浙江' ,long_name:'浙江省'},
    { en_name: 'anhui', name: '安徽',long_name:'安徽省' },
    { en_name: 'fujian', name: '福建' ,long_name:'福建省'},
    { en_name: 'jiangxi', name: '江西' ,long_name:'江西省'},
    { en_name: 'guangxi', name: '广西' ,long_name:'广西壮族自治区'},
    { en_name: 'hainan', name: '海南' ,long_name:'海南省'},
    { en_name: 'henan', name: '河南' ,long_name:'河南省'},
    { en_name: 'hunan', name: '湖南',long_name:'湖南省' },
    { en_name: 'shanxi2', name: '陕西',long_name:'陕西省' },
    { en_name: 'hubei', name: '湖北',long_name:'河北省' },
    { en_name: 'shanxi1', name: '山西',long_name:'山西省' },
    { en_name: 'neimenggu', name: '内蒙古' ,long_name:'内蒙古自治区'},
    { en_name: 'ningxia', name: '宁夏',long_name:'宁夏回族自治区' },
    { en_name: 'qinghai', name: '青海' ,long_name:'青海省'},
    { en_name: 'gansu', name: '甘肃',long_name:'甘肃省' },
    { en_name: 'xinjiang', name: '新疆',long_name:'新疆维吾尔自治区' },
    { en_name: 'sichuan', name: '四川',long_name:'四川省' },
    { en_name: 'guizhou', name: '贵州',long_name:'贵州省' },
    { en_name: 'yunnan', name: '云南' ,long_name:'云南省'},
    { en_name: 'chongqing', name: '重庆' ,long_name:'重庆市'},
    { en_name: 'xizang', name: '西藏',long_name:'西藏自治区' },
    { en_name: 'hongkong', name: '香港' ,long_name:'香港特别行政区'},
    { en_name: 'aomen', name: '澳门',long_name:'澳门特别行政区' },
    { en_name: 'taiwan', name: '台湾',long_name:'台湾省' }
  ]